replicaCount: 1

image:
  repository: compliance-api
  pullPolicy: Always
  namespace: c8b80a-tools
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

resources:
  cpu:
    limit: 250m
    request: 150m
  memory:
    limit: 384Mi
    request: 256Mi

database:
  secret: compliance-patroni
  service:
    name: compliance-patroni
    port: 5432

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-compliance
    cacheEnabled: true
    issuer: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://dev.loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://dev.loginproxy.gov.bc.ca
    realm: eao-epic
    adminClientId:
    adminClientSecret:
python:
  pythonBuffered: 1
  connectTimeout: 60
cdogs:  
  tokenEndpoint: https://dev.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
  apiEndpoint: https://cdogs-test.api.gov.bc.ca/api/v2
  clientId:
  clientSecret:
