app:
  name: compliance
  url: compliance-web-{{ .Release.Namespace }}.apps.gold.devops.gov.bc.ca
  api: https://compliance-api-{{ .Release.Namespace }}.apps.gold.devops.gov.bc.ca
  env: dev
resources:
  cpu:
    limit: 300m
    request: 250m
  memory:
    limit: 200Mi
    request: 100Mi
image:
  name: compliance-web
  tag: dev
  namespace: c8b80a-tools
  repository: image-registry.openshift-image-registry.svc:5000/c72cba-tools/
keycloak:
  url: "https://dev.loginproxy.gov.bc.ca"
  realm: eao-epic
  client: compliance-web
service:
  port: 8080
replicas:
  count: 1
mountPath: /usr/share/nginx/html/config/

