apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "VITE_API_URL": "{{ .Values.app.api }}",
        "VITE_ENV": "{{ .Values.app.env}}",
        "VITE_VERSION": "{{ .Values.app.version }}",
        "VITE_APP_TITLE": "EPIC.compliance",
        "VITE_APP_URL": "https://{{ .Values.app.url }}",
        "VITE_OIDC_AUTHORITY": "{{ .Values.keycloak.url }}",
        "VITE_CLIENT_ID": "{{ .Values.keycloak.client }}",
      }